### ISSUE TITLE
不解析url怎么回事，返回两个大括号

### ISSUE THREAD

**Issue by indiboy** [liliuwei/thinkphp-jump#1]
{"code":1,"msg":"登录成功","data":"","url":{},"wait":3}

**Comment by liliuwei** [comment]
> {"code":1,"msg":"登录成功","data":"","url":{},"wait":3}

你的怎么调用的呢？

**Comment by indiboy** [comment]
在AdminController最下方添加
    use \liliuwei\think\Jump;
}

class Login extends AdminController
{

然后调用。

**Comment by liliuwei** [comment]
> 在AdminController最下方添加
> use \liliuwei\think\Jump;
> }
> 
> class Login extends AdminController
> {
> 
> 然后调用。
你的success()方法里写的内容说下

**Comment by indiboy** [comment]
return $this->success('登录成功', 'index/index');
对了，我是ajax请求。

**Comment by indiboy** [comment]
我不太懂TP的机制，感谢回复。

**Comment by liliuwei** [comment]
修正了一下url生成，请更新一下最新扩展包再试试

**Comment by liliuwei** [comment]
> 我不太懂TP的机制，感谢回复。

修正了一下url生成，请更新一下最新扩展包再试试

**Comment by indiboy** [comment]
你的可以了，发现官方框架也有这个问题。
使用URL也是返回空，我也是醉了。
