### ISSUE TITLE
关于返回方法的问题请教一下。

### ISSUE THREAD

**Issue by indiboy** [liliuwei/thinkphp-jump#2]
这样可以正常生成
`$this->success('添加成功', (string)Route::buildUrl('admin/News/create', ['cid' => $data['cid']]));`
不可以正常生成
`$this->success('添加成功', url('admin/News/create', ['cid' => $data['cid']]));`

**Comment by liliuwei** [comment]
你说的调用方式都是支持的，如果还是有问题可以更新一下最新的版本再试试，或者把代码贴出来

使用最新的1.5版本
支持下面的方式
$this->success('登录成功', '/admin/index/index?type=1');
$this->success('登录成功', url('/admin/index/index',['type'=>1]));
$this->success('添加成功', (string)Route::buildUrl('/admin/index/index',['type'=>1]));

**Comment by liliuwei** [comment]
> 这样可以正常生成
> `$this->success('添加成功', (string)Route::buildUrl('admin/News/create', ['cid' => $data['cid']]));`
> 不可以正常生成
> `$this->success('添加成功', url('admin/News/create', ['cid' => $data['cid']]));`

你说的调用方式都是支持的，如果还是有问题可以更新一下最新的版本再试试，或者把代码贴出来

使用最新的1.5版本
支持下面的方式
$this->success('登录成功', '/admin/index/index?type=1');
$this->success('登录成功', url('/admin/index/index',['type'=>1]));
$this->success('添加成功', (string)Route::buildUrl('/admin/index/index',['type'=>1]));
