### ISSUE TITLE
success与error报错Trying to get property 'config' of non-object

### ISSUE THREAD

**Issue by lypeng29** [liliuwei/thinkphp-jump#4]
$this->app->config->get('jump.dispatch_success_tmpl')
这句报错~

**Comment by liliuwei** [comment]
仔细检查代码

**Comment by liliuwei** [comment]
> $this->app->config->get('jump.dispatch_success_tmpl')
> 这句报错~

看文档

**Comment by lypeng29** [comment]
嗯，发现了，我的父类construct没传App~

**Comment by lypeng29** [comment]
如果子类有自己的construct，每个页面都的use think\App,然后parent::__construct($app); 这里需要再传一遍，感觉不是很方便~ 我还是想别的办法~不用类库了~
