### ISSUE TITLE
Call to a member function isJson() on null

### ISSUE THREAD

**Issue by codelibo** [liliuwei/thinkphp-jump#6]
已在BaseController 基类 use \liliuwei\think\Jump; 继承基类后还总是跳转报错，不知是何原因??
#0 [0]Error in Jump.php line 163
Call to a member function isJson() on null
    }

    /**
     * 获取当前的response 输出类型
     * @access protected
     * @return string
     */
    protected function getResponseType()
    {
        return $this->request->isJson() || $this->request->isAjax() ? 'json' : 'html';
    }
}

**Comment by liliuwei** [comment]
建议再熟悉一下trait 的用法，了解一下优先级和冲突的解决

手册地址：https://www.php.net/manual/zh/language.oop5.traits.php

用框架带的initialize() 代替 __construct来实现一些功能
